[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'romainl/Apprentice'
if = "has('nvim')"

[[plugins]]
repo = 'airblade/vim-gitgutter'
if = "has('nvim')"

[[plugins]]
repo = 'Yggdroot/indentLine'
if = "has('nvim')"
