[[plugins]]
repository = 'Shougo/context_filetype.vim'
filetypes = 'all'

[[plugins]]
repository = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neopairs.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert = 1
filetypes = 'snippet'

[[plugins]]
repository = 'Shougo/neco-vim'
filetypes = 'vim'
insert = 1

[[plugins]]
repository = 'Shougo/neoinclude.vim'
filetypes = 'all'

[[plugins]]
repository = 'Shougo/neco-syntax'
insert = 1

[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes = 'python'

[[plugins]]
repository = 'honza/vim-snippets'
insert = 1
filetypes = 'all'

[[plugins]]
repository = 'euclio/vim-markdown-composer'
filetypes = 'md'
