[[plugins]]
repository = 'Shougo/context_filetype.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neopairs.vim'
on_i = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repository = 'Shougo/neco-vim'
on_i = 1
on_ft = 'vim'

[[plugins]]
repository = 'Shougo/neoinclude.vim'
on_ft = 'all'

[[plugins]]
repository = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repository = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repository = 'honza/vim-snippets'
on_i = 1
on_ft = 'all'

[[plugins]]
repository = 'euclio/vim-markdown-composer'
on_ft = ['mkd', 'markdown']

[[plugins]]
repository = 'amperser/proselint'
on_ft = ['mkd', 'markdown']
