[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repository = 'altercation/vim-colors-solarized'

[[plugins]]
repository = 'airblade/vim-gitgutter'

[[plugins]]
repository = 'bling/vim-airline'

[[plugins]]
repository = 'Yggdroot/indentLine'

[[plugins]]
repository = 'benekastah/neomake'

[[plugins]]
repository = 'tpope/vim-fugitive'
