[[plugins]]
repository = 'Shougo/tabpagebuffer.vim'
filetypes = 'all'

[[plugins]]
repository = 'Shougo/neopairs.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'Shougo/context_filetype.vim']
insert = 1
filetypes = 'snippet'
unite_sources = ['neosnippet', 'neosnippet/user', 'neosnippet/runtime']

[[plugins]]
repository = 'Shougo/junkfile.vim'
unite_sources = 'junkfile'

[[plugins]]
repository = 'Shougo/neco-vim'
filetypes = 'vim'
insert = 1

[[plugins]]
repository = 'Shougo/neoinclude.vim'
filetypes = 'all'

[[plugins]]
repository = 'Shougo/neco-syntax'
insert = 1

[[plugins]]
repository = 'Shougo/vinarise.vim'

  [plugins.commands]
  name = 'Vinarise'
  complete = 'file'

[[plugins]]
repository = 'davidhalter/jedi-vim'
filetypes = 'python'
